export const mockPlayer = {
  nickname: "PlayerUnknown_KR",
  platform: "steam" as const,
  season: {
    kda: 1.82,
    winRate: 8.2,
    avgDamage: 387,
    headshotRate: 22.1,
    topTenRate: 31.4,
    gamesPlayed: 142,
    percentileKDA: 72,
    percentileDamage: 75,
    percentileWinRate: 68,
    percentileHeadshot: 70,
  },
  rankedTier: {
    squad: { tier: "Gold", subTier: "II", rp: 2340, wins: 25, losses: 36, games: 61, kills: 187, kda: 5.19, winRate: 41.0, avgDamage: 547 },
    duo:   { tier: "Gold", subTier: "I",  rp: 2480, wins: 18, losses: 22, games: 40, kills: 134, kda: 6.09, winRate: 45.0, avgDamage: 523 },
    solo:  null,
  },
  modeStats: {
    squad: { kda: 1.82, winRate: 8.2,  avgDamage: 387, headshotRate: 22.1, topTenRate: 31.4, gamesPlayed: 132, wins: 11, top10s: 41, losses: 121, avgRank: 6.1,  kills: 221 },
    duo:   { kda: 2.10, winRate: 10.5, avgDamage: 412, headshotRate: 24.3, topTenRate: 35.8, gamesPlayed: 61,  wins: 6,  top10s: 22, losses: 55,  avgRank: 5.3,  kills: 128 },
    solo:  { kda: 1.45, winRate: 4.8,  avgDamage: 298, headshotRate: 19.7, topTenRate: 21.2, gamesPlayed: 42,  wins: 2,  top10s: 9,  losses: 40,  avgRank: 8.7,  kills: 58  },
  },
  aiAnalysis: {
    styleKey: "assault" as const,
    style: "공격형" as const,
    summary: "최근 10게임 분석: 초반 교전 참여율이 높으나 중거리 딜 효율이 낮습니다. 스코프 활용을 늘리면 KDA 개선 여지가 있습니다.",
    improvements: [
      "중거리 교전 시 2배율 이상 스코프 사용 권장",
      "팀 합류 전 단독 교전 빈도를 줄이세요",
      "외곽 낙하 후 안정적 파밍 패턴 고려",
    ],
  },
  dangerScore: 74,
  dangerDetails: {
    recentKDA: 4.1,
    recentDamage: 420,
    recentHeadshot: 28,
    preferredWeapon: "M416",
    playStyle: "공격형" as const,
  },
  recentMatches: [
    { id:"m1",  map:"Erangel", mode:"스쿼드", rank:1,  kills:8, assists:2, damage:621, survived:1842, isWin:true,  isRanked:true,  totalPlayers:100, distanceKm:6.2, weapon:"M416",
      teammates:[{name:"Sniper_Lee",kills:3,damage:245},{name:"Support_Park",kills:1,damage:180},{name:"Survive_Choi",kills:0,damage:95}] },
    { id:"m2",  map:"Miramar", mode:"스쿼드", rank:4,  kills:3, assists:1, damage:298, survived:1203, isWin:false, isRanked:true,  totalPlayers:100, distanceKm:4.8, weapon:"AKM",
      teammates:[{name:"Ace_Kim",kills:5,damage:412},{name:"Support_Park",kills:1,damage:120},{name:"Survive_Choi",kills:2,damage:198}] },
    { id:"m3",  map:"Taego",   mode:"솔로",   rank:2,  kills:5, assists:0, damage:512, survived:1654, isWin:false, isRanked:false, totalPlayers:64,  distanceKm:5.1, weapon:"AWM", teammates:[] },
    { id:"m4",  map:"Erangel", mode:"스쿼드", rank:7,  kills:1, assists:3, damage:187, survived:891,  isWin:false, isRanked:false, totalPlayers:100, distanceKm:3.4, weapon:"UMP45",
      teammates:[{name:"Ace_Kim",kills:4,damage:380},{name:"Sniper_Lee",kills:2,damage:220},{name:"Survive_Choi",kills:0,damage:55}] },
    { id:"m5",  map:"Sanhok",  mode:"스쿼드", rank:1,  kills:6, assists:1, damage:445, survived:1234, isWin:true,  isRanked:true,  totalPlayers:100, distanceKm:4.3, weapon:"M416",
      teammates:[{name:"Ace_Kim",kills:4,damage:310},{name:"Sniper_Lee",kills:2,damage:198},{name:"Support_Park",kills:0,damage:87}] },
    { id:"m6",  map:"Vikendi", mode:"듀오",   rank:3,  kills:4, assists:0, damage:367, survived:1401, isWin:false, isRanked:false, totalPlayers:50,  distanceKm:5.7, weapon:"Kar98k",
      teammates:[{name:"Sniper_Lee",kills:6,damage:512}] },
    { id:"m7",  map:"Miramar", mode:"솔로",   rank:1,  kills:9, assists:0, damage:734, survived:2103, isWin:true,  isRanked:true,  totalPlayers:64,  distanceKm:7.8, weapon:"AWM", teammates:[] },
    { id:"m8",  map:"Erangel", mode:"스쿼드", rank:12, kills:0, assists:1, damage:98,  survived:423,  isWin:false, isRanked:false, totalPlayers:100, distanceKm:2.1, weapon:"S12K",
      teammates:[{name:"Ace_Kim",kills:3,damage:287},{name:"Sniper_Lee",kills:1,damage:145},{name:"Survive_Choi",kills:0,damage:32}] },
    { id:"m9",  map:"Deston",  mode:"스쿼드", rank:1,  kills:7, assists:2, damage:589, survived:1987, isWin:true,  isRanked:true,  totalPlayers:100, distanceKm:6.9, weapon:"M416",
      teammates:[{name:"Ace_Kim",kills:5,damage:398},{name:"Sniper_Lee",kills:2,damage:210},{name:"Support_Park",kills:1,damage:134}] },
    { id:"m10", map:"Rondo",   mode:"스쿼드", rank:6,  kills:2, assists:0, damage:223, survived:1102, isWin:false, isRanked:true,  totalPlayers:100, distanceKm:4.5, weapon:"Beryl M762",
      teammates:[{name:"Sniper_Lee",kills:4,damage:345},{name:"Survive_Choi",kills:1,damage:98},{name:"Support_Park",kills:0,damage:45}] },
    { id:"m11", map:"Erangel", mode:"솔로",   rank:5,  kills:3, assists:0, damage:312, survived:1543, isWin:false, isRanked:false, totalPlayers:64,  distanceKm:5.3, weapon:"SKS", teammates:[] },
    { id:"m12", map:"Taego",   mode:"스쿼드", rank:1,  kills:10,assists:1, damage:812, survived:2234, isWin:true,  isRanked:true,  totalPlayers:100, distanceKm:8.4, weapon:"M416",
      teammates:[{name:"Ace_Kim",kills:6,damage:480},{name:"Sniper_Lee",kills:3,damage:267},{name:"Survive_Choi",kills:0,damage:78}] },
    { id:"m13", map:"Miramar", mode:"듀오",   rank:2,  kills:5, assists:1, damage:467, survived:1801, isWin:false, isRanked:false, totalPlayers:50,  distanceKm:6.1, weapon:"Kar98k",
      teammates:[{name:"Sniper_Lee",kills:7,damage:598}] },
    { id:"m14", map:"Sanhok",  mode:"스쿼드", rank:9,  kills:2, assists:2, damage:198, survived:934,  isWin:false, isRanked:true,  totalPlayers:100, distanceKm:3.8, weapon:"UMP45",
      teammates:[{name:"Ace_Kim",kills:3,damage:264},{name:"Support_Park",kills:1,damage:112},{name:"Survive_Choi",kills:0,damage:37}] },
    { id:"m15", map:"Vikendi", mode:"솔로",   rank:1,  kills:6, assists:0, damage:543, survived:1923, isWin:true,  isRanked:true,  totalPlayers:64,  distanceKm:7.2, weapon:"Kar98k", teammates:[] },
    { id:"m16", map:"Erangel", mode:"스쿼드", rank:3,  kills:4, assists:3, damage:387, survived:1654, isWin:false, isRanked:false, totalPlayers:100, distanceKm:5.6, weapon:"M416",
      teammates:[{name:"Ace_Kim",kills:5,damage:412},{name:"Sniper_Lee",kills:3,damage:298},{name:"Support_Park",kills:0,damage:67}] },
    { id:"m17", map:"Deston",  mode:"스쿼드", rank:18, kills:0, assists:0, damage:54,  survived:312,  isWin:false, isRanked:true,  totalPlayers:100, distanceKm:1.4, weapon:"Pan",
      teammates:[{name:"Survive_Choi",kills:2,damage:187},{name:"Support_Park",kills:1,damage:134},{name:"Sniper_Lee",kills:0,damage:43}] },
    { id:"m18", map:"Taego",   mode:"듀오",   rank:1,  kills:8, assists:2, damage:694, survived:2098, isWin:true,  isRanked:false, totalPlayers:50,  distanceKm:7.5, weapon:"M416",
      teammates:[{name:"Ace_Kim",kills:9,damage:734}] },
    { id:"m19", map:"Rondo",   mode:"스쿼드", rank:4,  kills:3, assists:1, damage:276, survived:1387, isWin:false, isRanked:true,  totalPlayers:100, distanceKm:5.0, weapon:"AKM",
      teammates:[{name:"Sniper_Lee",kills:5,damage:423},{name:"Ace_Kim",kills:2,damage:198},{name:"Survive_Choi",kills:1,damage:87}] },
    { id:"m20", map:"Miramar", mode:"솔로",   rank:8,  kills:4, assists:0, damage:421, survived:1689, isWin:false, isRanked:false, totalPlayers:64,  distanceKm:6.3, weapon:"SKS", teammates:[] },
  ],
  weapons: [
    { name: "M416", kills: 234, headshotRate: 28, games: 87 },
    { name: "AWM", kills: 89, headshotRate: 61, games: 34 },
    { name: "UMP45", kills: 67, headshotRate: 19, games: 52 },
    { name: "AKM", kills: 54, headshotRate: 22, games: 41 },
    { name: "SKS", kills: 31, headshotRate: 45, games: 28 },
  ],
};

export const mockSquad = {
  members: [
    {
      nickname: "Ace_Kim",
      role: "돌격형" as const,
      kda: 4.1,
      damage: 450,
      headshotRate: 31,
      winRate: 12,
      platform: "steam" as const,
    },
    {
      nickname: "Sniper_Lee",
      role: "저격형" as const,
      kda: 3.8,
      damage: 380,
      headshotRate: 55,
      winRate: 9,
      platform: "steam" as const,
    },
    {
      nickname: "Support_Park",
      role: "지원형" as const,
      kda: 2.1,
      damage: 290,
      headshotRate: 18,
      winRate: 8,
      platform: "steam" as const,
    },
    {
      nickname: "Survive_Choi",
      role: "생존형" as const,
      kda: 1.9,
      damage: 210,
      headshotRate: 14,
      winRate: 11,
      platform: "steam" as const,
    },
  ],
  synergyScore: 82,
  synergyComment:
    "화력과 정찰의 균형이 잡힌 팀입니다. 생존 전략만 보완하면 탑10 진입률이 크게 올라갑니다.",
  strengths: ["화력", "정밀 저격"],
  weaknesses: ["생존력", "힐링 타이밍"],
};

export type PlayerRole = "돌격형" | "저격형" | "지원형" | "생존형";
export type PlayStyle = "공격형" | "존버형" | "균형형";
export type Platform = "steam" | "kakao";
